pipeline:
    name: pipeline4
    identifier: pipeline4
    allowStageExecutions: false
    projectIdentifier: rtdb
    orgIdentifier: default
    description: ""
    tags: {}
    stages:
        - stage:
              name: stage1
              identifier: stage1
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: rtdb
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables:
                                  - name: TWITTER_CONSUMER_KEY
                                    type: Secret
                                    value: TWITTER_CONSUMER_KEY
                                  - name: TWITTER_CONSUMER_SECRET
                                    type: Secret
                                    value: TWITTER_CONSUMER_SECRET
                                  - name: TWITTER_TOKEN_KEY
                                    type: Secret
                                    value: TWITTER_TOKEN_KEY
                                  - name: TWITTER_TOKEN_SECRET
                                    type: Secret
                                    value: TWITTER_TOKEN_SECRET
                              manifests:
                                  - manifest:
                                        identifier: manifest
                                        type: HelmChart
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: github
                                                    gitFetchType: Branch
                                                    folderPath: helm/rtdb
                                                    branch: kaniko
                                            skipResourceVersioning: false
                                            helmVersion: V2
                                  - manifest:
                                        identifier: rtdbyaml
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: github
                                                    gitFetchType: Branch
                                                    paths:
                                                        - helm/rtdb/values.yaml
                                                    repoName: rtdb
                                                    branch: kaniko
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: dockerhub
                                          imagePath: chicagozer/rtdb
                                          tag: harness
                                      type: DockerRegistry
                  infrastructure:
                      environmentRef: nonprod
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: mycluster
                              namespace: rtdb
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
